
# Enable Doctrine to map the provided entities
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    SonataUserBundle: ~
sonata_user:
    #admin:
    #    user:
    #        class: Oxind\UserBundle\Admin\UserAdmin
    security_acl:             false
    table:
        user_group:           oxind_user_user_group

    class:
        user:         Oxind\UserBundle\Entity\User
        group:        Oxind\UserBundle\Entity\Group

#    impersonating:
#        route:                page_slug
#        parameters:           { path: / }

    manager_type:             orm

    profile:
        form:
            type:                 sonata_user_profile
            handler:              sonata.user.profile.form.handler.default
            name:                 sonata_user_profile_form
            validation_groups:
                # Defaults:
                - Profile
                - Default

#parameters:
#    sonata.user.admin.user.entity:  Oxind\UserBundle\Entity\User
#    sonata.user.admin.group.entity: Oxind\UserBundle\Entity\Group