oxind_feedback:
    db_driver: orm
    feedback_per_page : 1
    user_class: Oxind\UserBundle\Entity\User
    fixtures: Oxind/DashboardBundle/DataFixtures/Fixtures 
    class:
        model:
            feedback: Oxind\DashboardBundle\Entity\Feedback
            feedbacktype: Oxind\DashboardBundle\Entity\FeedbackType
            vote: Oxind\DashboardBundle\Entity\Vote
            timeline: Oxind\DashboardBundle\Entity\Timeline
            feedbackdisplay: Oxind\DashboardBundle\Entity\FeedbackDisplay
            